### PR TITLE
NEWTS-111: OpenNMS Integration with cloud-hosted Cassandra

### PR DESCRIPTION
**Pull request by jeffgdotorg**
- Updated Cassandra driver to v3.8.0
- Added accessors for cloudConnectBundle
- Hooked up existing username and password as client-ID and client-secret when
  a cloud-connect bundle is configured
- Updated logging

### CODE REVIEW

**Comment by j-white** [comment]
Changes look good. I think we may also need to bump the version of [cassandra-unit](https://github.com/OpenNMS/newts/blob/master/cassandra/pom.xml#L23) that is used for the tests to pass.

We also need to understand any changes to the transient dependencies made by upgrading the Cassandra driver as this may impact which versions of OpenNMS we can pull this into.

**Comment by j-white** [comment]
Nice, it's green! I can help take a look at comparing the dependency changes.

**Comment by j-white** [comment]
Transient dependencies look good - only a new dependency on `com.fasterxml.jackson.core:jackson-databind:jar:2.5.4:compile` - version if Netty remains unchanged.

**Review by j-white — APPROVED** [review]

**Comment by RangerRick** [comment]
Just double-checked deps after fixing tests and bumping to 3.11.0, and it looks like in addition to jackson-databind, it ends up bumping netty and adding a few things as well, but on the opennms side we're actually already using/overriding newer versions anyways.  We'll just want to double-check what gets pulled in before and after, but since this would go to `develop` it should be OK.

```
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.5.4:compile
[INFO] |  |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.5.0:compile
[INFO] |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.5.4:compile
...
[INFO]    |  +- commons-codec:commons-codec:jar:1.9:compile
...
[INFO]    +- io.netty:netty-handler:jar:4.0.44.Final:compile
[INFO]    |  +- io.netty:netty-buffer:jar:4.0.44.Final:compile
[INFO]    |  |  \- io.netty:netty-common:jar:4.0.44.Final:compile
[INFO]    |  +- io.netty:netty-transport:jar:4.0.44.Final:compile
[INFO]    |  \- io.netty:netty-codec:jar:4.0.44.Final:compile
[INFO]    +- org.apache.thrift:libthrift:jar:0.9.2:compile
[INFO]    |  +- org.apache.httpcomponents:httpclient:jar:4.2.5:compile
[INFO]    |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.2.4:compile
[INFO]    +- net.java.dev.jna:jna:jar:4.1.0:compile
```

**Comment by j-white** [comment]
Can be configured using "driver settings file" exposed in 3.0.0

**Pull request closed without merging**
